# Site settings
title: My Shelf
description: My Shelf
baseurl: /myshelf # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

baseBookshelfUrl: /bookshelf-data

#gplus_username:  lorem_ipsum
# Google-analytics
google-analytics:
  id: "UA-1749812-7"

exclude: ['package.json', 'src' , 'node_modules']
